name: melnet
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - absl-py=0.9.0=py38_0
  - attrdict=2.0.1=py_0
  - attrs=19.3.0=py_0
  - audioread=2.1.8=py38h32f6830_2
  - backcall=0.2.0=py_0
  - blas=1.0=mkl
  - bleach=3.1.5=py_0
  - blinker=1.4=py38_0
  - brotlipy=0.7.0=py38h7b6447c_1000
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.15.0=h7b6447c_1001
  - ca-certificates=2020.6.24=0
  - cachetools=4.1.0=py_1
  - certifi=2020.6.20=py38_0
  - cffi=1.14.0=py38he30daa8_1
  - chardet=3.0.4=py38_1003
  - click=7.1.2=py_0
  - cryptography=2.9.2=py38h1ba5d50_0
  - cudatoolkit=9.2=0
  - cycler=0.10.0=py38_0
  - dbus=1.13.16=hb2f20db_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py38_0
  - expat=2.2.9=he6710b0_2
  - ffmpeg=4.2.2=h20bf706_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.10.2=h5ab3b9f_0
  - gettext=0.19.8.1=h9b4dc7a_1
  - glib=2.65.0=h3eb4bd4_0
  - gmp=6.1.2=h6c8ec71_1
  - gnutls=3.6.5=h71b1129_1002
  - google-auth=1.17.2=py_0
  - google-auth-oauthlib=0.4.1=py_2
  - grpcio=1.27.2=py38hf8bcb03_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb31296c_0
  - icu=58.2=he6710b0_3
  - idna=2.10=py_0
  - importlib-metadata=1.7.0=py38_0
  - importlib_metadata=1.7.0=0
  - intel-openmp=2020.1=217
  - ipykernel=5.3.2=py38h5ca1d4c_0
  - ipython=7.16.1=py38h5ca1d4c_0
  - ipython_genutils=0.2.0=py38_0
  - ipywidgets=7.5.1=py_0
  - jedi=0.17.1=py38_0
  - jinja2=2.11.2=py_0
  - joblib=0.16.0=py_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.2.0=py38_0
  - jupyter=1.0.0=py38_7
  - jupyter_client=6.1.6=py_0
  - jupyter_console=6.1.0=py_0
  - jupyter_core=4.6.3=py38_0
  - kiwisolver=1.2.0=py38hfd86e86_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libflac=1.3.3=he1b5a44_0
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libllvm9=9.0.1=h4a3c616_1
  - libogg=1.3.2=h7b6447c_0
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.12.3=hd408876_0
  - librosa=0.7.2=py_1
  - libsndfile=1.0.28=he1b5a44_1000
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libvorbis=1.3.6=h7b6447c_0
  - libvpx=1.7.0=h439df22_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=he19cac6_1
  - llvmlite=0.33.0=py38hc6ec683_1
  - lz4-c=1.9.2=he6710b0_0
  - markdown=3.1.1=py38_0
  - markupsafe=1.1.1=py38h7b6447c_0
  - matplotlib=3.2.2=0
  - matplotlib-base=3.2.2=py38hef1b27d_0
  - mistune=0.8.4=py38h7b6447c_1000
  - mkl=2020.1=217
  - mkl-service=2.3.0=py38he904b0f_0
  - mkl_fft=1.1.0=py38h23d657b_0
  - mkl_random=1.1.1=py38h0573a6f_0
  - nbconvert=5.6.1=py38_0
  - nbformat=5.0.7=py_0
  - ncurses=6.2=he6710b0_1
  - nettle=3.4.1=hbb512f6_0
  - ninja=1.9.0=py38hfd86e86_0
  - notebook=6.0.3=py38_0
  - numba=0.50.1=py38h0573a6f_1
  - numpy=1.18.5=py38ha1c710e_0
  - numpy-base=1.18.5=py38hde5b4d6_0
  - oauthlib=3.1.0=py_0
  - olefile=0.46=py_0
  - openh264=2.1.0=hd408876_0
  - openssl=1.1.1g=h7b6447c_0
  - packaging=20.4=py_0
  - pandas=1.0.5=py38h0573a6f_0
  - pandoc=2.10=0
  - pandocfilters=1.4.2=py38_1
  - parso=0.7.0=py_0
  - pcre=8.44=he6710b0_0
  - pexpect=4.8.0=py38_0
  - pickleshare=0.7.5=py38_1000
  - pillow=7.2.0=py38hb39fc2d_0
  - pip=20.1.1=py38_1
  - prometheus_client=0.8.0=py_0
  - prompt-toolkit=3.0.5=py_0
  - prompt_toolkit=3.0.5=0
  - protobuf=3.12.3=py38he6710b0_0
  - ptyprocess=0.6.0=py38_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=py_2
  - pygments=2.6.1=py_0
  - pyjwt=1.7.1=py38_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py38h05f1152_4
  - pyrsistent=0.16.0=py38h7b6447c_0
  - pysocks=1.7.1=py38_0
  - pysoundfile=0.10.2=py_1001
  - python=3.8.3=hcff3b4d_2
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytorch=1.5.1=py3.8_cuda9.2.148_cudnn7.6.3_0
  - pytz=2020.1=py_0
  - pyyaml=5.3.1=py38h7b6447c_1
  - pyzmq=19.0.1=py38he6710b0_1
  - qt=5.9.7=h5867ecd_1
  - qtconsole=4.7.5=py_0
  - qtpy=1.9.0=py_0
  - readline=8.0=h7b6447c_0
  - requests=2.24.0=py_0
  - requests-oauthlib=1.3.0=py_0
  - resampy=0.2.2=py_0
  - rsa=4.0=py_0
  - scikit-learn=0.23.1=py38h423224d_0
  - scipy=1.5.0=py38h0b6359f_0
  - send2trash=1.5.0=py38_0
  - setuptools=49.2.0=py38_0
  - sip=4.19.13=py38he6710b0_0
  - six=1.15.0=py_0
  - sqlite=3.32.3=h62c20be_0
  - tbb=2020.0=hfd86e86_0
  - tensorboard=2.2.1=pyh532a8cf_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - terminado=0.8.3=py38_0
  - testpath=0.4.4=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hbc83047_0
  - torchaudio=0.5.1=py38
  - torchvision=0.6.1=py38_cu92
  - tornado=6.0.4=py38h7b6447c_1
  - traitlets=4.3.3=py38_0
  - urllib3=1.25.9=py_0
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py38_1
  - werkzeug=1.0.1=py_0
  - wheel=0.34.2=py38_0
  - widgetsnbextension=3.5.1=py38_0
  - x264=1!157.20191217=h7b6447c_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.2=he6710b0_2
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h0b5b093_0
prefix: /home/jorge/anaconda3/envs/melnet

